title: Maximus Perez home page
page-top-title: Maximus Perez
top-section-bg-text: Computer Science
home-subtitle: Maximus Perez &ensp;|&ensp;English
copyright-text: '&copy; Maximus Perez 2025. All Rights Reserved.'
